using System;
using System.Drawing;
using System.Windows.Forms;
namespace StudentAttendanceSystemVS2012
{
 static class Program{[STAThread] static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{Application.Run(new LoginForm(new Database()));}catch(Exception ex){MessageBox.Show(ex.Message,"Startup error",MessageBoxButtons.OK,MessageBoxIcon.Error);}}}
 sealed class LoginForm:Form
 {
  readonly Database db;readonly TextBox user=new TextBox(),password=new TextBox();
  public LoginForm(Database database){db=database;Text="University Attendance Management System - Login";Size=new Size(1080,680);MinimumSize=new Size(900,600);StartPosition=FormStartPosition.CenterScreen;BackColor=Ui.Background;Font=new Font("Segoe UI",10);password.UseSystemPasswordChar=true;var left=new Panel{Dock=DockStyle.Left,Width=430,BackColor=Ui.Primary};left.Controls.Add(new Label{Text="●  UCSPyay",Font=new Font("Segoe UI Semibold",35),ForeColor=Color.White,AutoSize=true,Location=new Point(48,165)});left.Controls.Add(new Label{Text="UNIVERSITY ATTENDANCE PORTAL",Font=new Font("Segoe UI Semibold",10),ForeColor=Color.FromArgb(151,175,180),AutoSize=true,Location=new Point(58,220)});left.Controls.Add(new Label{Text="Secure attendance, clear insights,\nbetter academic outcomes.",Font=new Font("Segoe UI",11),ForeColor=Color.FromArgb(190,204,235),AutoSize=true,Location=new Point(58,290)});var card=new Panel{Size=new Size(440,420),BackColor=Color.White};var p=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(48,45,48,35)};p.Controls.Add(new Label{Text="Welcome back",Font=new Font("Segoe UI Semibold",23),AutoSize=true,ForeColor=Ui.Text,Margin=new Padding(0,0,0,5)});p.Controls.Add(new Label{Text="Sign in to continue to your dashboard",AutoSize=true,ForeColor=Ui.Muted,Margin=new Padding(0,0,0,24)});p.Controls.Add(Ui.Label("USERNAME"));user.Width=330;p.Controls.Add(user);p.Controls.Add(Ui.Label("PASSWORD"));password.Width=330;p.Controls.Add(password);p.Controls.Add(new Label{Height=10});var b=Ui.Button("Sign in",Login);b.Width=330;b.Height=46;p.Controls.Add(b);card.Controls.Add(p);var host=new Panel{Dock=DockStyle.Fill,BackColor=Ui.Background};host.Controls.Add(card);EventHandler center=delegate{card.Left=Math.Max(30,(host.ClientSize.Width-card.Width)/2);card.Top=Math.Max(30,(host.ClientSize.Height-card.Height)/2);};host.Resize+=center;Controls.Add(host);Controls.Add(left);center(null,EventArgs.Empty);AcceptButton=b;Ui.Style(this);}
  void Login(object sender,EventArgs e){var t=db.Query("SELECT u.UserId,u.Username,u.PasswordHash,u.FullName,u.Role,t.TeacherId FROM Users u LEFT JOIN Teachers t ON t.UserId=u.UserId WHERE u.Username=@u AND u.IsActive=1",new System.Data.SqlClient.SqlParameter("@u",user.Text.Trim()));if(t.Rows.Count!=1||!PasswordHasher.Verify(password.Text,Convert.ToString(t.Rows[0]["PasswordHash"]))){MessageBox.Show("Invalid username or password.");return;}var r=t.Rows[0];Hide();using(var f=new MainForm(db,Convert.ToInt32(r["UserId"]),r["TeacherId"]==DBNull.Value?(int?)null:Convert.ToInt32(r["TeacherId"]),Convert.ToString(r["Username"]),Convert.ToString(r["FullName"]),Convert.ToString(r["Role"])))f.ShowDialog();user.Clear();password.Clear();Show();}
 }
}


