using Microsoft.Data.SqlClient;
using System.Data;
using StudentAttendanceSystem.Forms.Shared;
using StudentAttendanceSystem.Models;
using StudentAttendanceSystem.Services;

namespace StudentAttendanceSystem.Forms.Admin;

public sealed class AdminManagementControl:UserControl
{
    readonly AppServices s;readonly string mode;readonly DataGridView grid=new(){Dock=DockStyle.Fill};readonly TextBox search=new(){Width=210,PlaceholderText="Search this list..."};readonly Label pageLabel=new(){AutoSize=true,Margin=new Padding(12,12,12,0),ForeColor=Ui.Muted};object? loadedData;int currentPage=1;const int PageSize=10;
    public AdminManagementControl(AppServices s,string mode){this.s=s;this.mode=mode;Ui.ConfigureGrid(grid);var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=68,Padding=new Padding(8)};bar.Controls.AddRange([Ui.Label("Search"),search,Ui.Button($"Add {DisplayEntity}",(_,_)=>Ui.Safe(AddAsync)),Ui.SecondaryButton("Edit selected",(_,_)=>Ui.Safe(EditAsync)),Ui.SecondaryButton("Activate / deactivate",(_,_)=>Ui.Safe(ToggleActiveAsync)),Ui.SecondaryButton("Refresh",(_,_)=>Ui.Safe(LoadAsync))]);var pager=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(10,5,18,5),BackColor=Ui.Surface};pager.Controls.Add(Ui.SecondaryButton("Next",(_,_)=>{currentPage++;ApplySearch();}));pager.Controls.Add(pageLabel);pager.Controls.Add(Ui.SecondaryButton("Previous",(_,_)=>{if(currentPage>1)currentPage--;ApplySearch();}));search.TextChanged+=(_,_)=>{currentPage=1;ApplySearch();};Controls.Add(grid);Controls.Add(pager);Controls.Add(bar);Load+=(_,_)=>Ui.Safe(LoadAsync);grid.CellFormatting+=StatusFormatting;}
    string DisplayEntity=>mode switch{"Teachers"=>"lecturer","Rooms"=>"class","Subjects"=>"course","Timetables"=>"timetable session",_=>"assignment"};
    async Task LoadAsync(){loadedData=mode switch{ "Teachers"=>await s.Db.QueryAsync("SELECT t.TeacherId,t.TeacherCode,t.FullName,t.Phone,u.Username,u.IsActive FROM Teachers t JOIN Users u ON u.UserId=t.UserId ORDER BY t.FullName",r=>new{Id=r.GetInt32(0),Code=r.GetString(1),Name=r.GetString(2),Phone=r.IsDBNull(3)?"":r.GetString(3),Username=r.GetString(4),Active=r.GetBoolean(5)}),"Rooms"=>await s.Db.QueryAsync("SELECT r.RoomId,r.RoomName,r.Department,r.ProgramName,r.StudyLevel,r.Semester,r.AcademicYear,COALESCE(t.FullName,'') HomeRoomTeacher,r.IsActive FROM Rooms r LEFT JOIN Teachers t ON t.TeacherId=r.HomeRoomTeacherId ORDER BY r.ProgramName,r.StudyLevel,r.RoomName",r=>new{Id=r.GetInt32(0),ClassSection=r.GetString(1),Department=r.GetString(2),Program=r.GetString(3),StudyLevel=r.GetString(4),Semester=r.GetByte(5),AcademicYear=r.GetString(6),HomeTeacher=r.GetString(7),Active=r.GetBoolean(8)}),"Subjects"=>await s.Db.QueryAsync("SELECT SubjectId,SubjectCode,SubjectName,IsActive FROM Subjects ORDER BY SubjectName",r=>new{Id=r.GetInt32(0),Code=r.GetString(1),Name=r.GetString(2),Active=r.GetBoolean(3)}),"Timetables"=>await s.Db.QueryAsync("SELECT tt.TimetableId,r.RoomName,s.SubjectCode+' - '+s.SubjectName,t.FullName,CHOOSE(tt.DayOfWeek,'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'),tt.StartTime,tt.EndTime,tt.EffectiveFrom,tt.EffectiveTo,tt.IsActive FROM Timetables tt JOIN Rooms r ON r.RoomId=tt.RoomId JOIN Subjects s ON s.SubjectId=tt.SubjectId JOIN Teachers t ON t.TeacherId=tt.TeacherId ORDER BY tt.DayOfWeek,tt.StartTime",r=>new{Id=r.GetInt32(0),Class=r.GetString(1),Course=r.GetString(2),Lecturer=r.GetString(3),Day=r.GetString(4),Start=r.GetTimeSpan(5).ToString(@"hh\:mm"),End=r.GetTimeSpan(6).ToString(@"hh\:mm"),From=r.GetDateTime(7).ToShortDateString(),To=r.GetDateTime(8).ToShortDateString(),Active=r.GetBoolean(9)}),_=>await s.Db.QueryAsync("SELECT ta.AssignmentId,t.FullName Teacher,r.RoomName Room,s.SubjectName Subject,ta.AcademicYear,ta.IsActive FROM TeacherAssignments ta JOIN Teachers t ON t.TeacherId=ta.TeacherId JOIN Rooms r ON r.RoomId=ta.RoomId JOIN Subjects s ON s.SubjectId=ta.SubjectId ORDER BY t.FullName,r.RoomName,s.SubjectName",r=>new{Id=r.GetInt32(0),Teacher=r.GetString(1),Room=r.GetString(2),Subject=r.GetString(3),Year=r.GetString(4),Active=r.GetBoolean(5)})};ApplySearch();}
    void ApplySearch(){if(loadedData is not System.Collections.IEnumerable rows)return;var q=search.Text.Trim();var filtered=new List<object>();foreach(var x in rows)if(x is not null&&(string.IsNullOrEmpty(q)||x.GetType().GetProperties().Any(p=>p.GetValue(x)?.ToString()?.Contains(q,StringComparison.OrdinalIgnoreCase)==true)))filtered.Add(x);filtered=filtered.OrderBy(x=>Convert.ToInt32(x.GetType().GetProperty("Id")?.GetValue(x)??0)).ToList();var pages=Math.Max(1,(int)Math.Ceiling(filtered.Count/(double)PageSize));currentPage=Math.Clamp(currentPage,1,pages);var pageRows=filtered.Skip((currentPage-1)*PageSize).Take(PageSize).ToList();var table=new DataTable();table.Columns.Add("No",typeof(int));var properties=filtered.FirstOrDefault()?.GetType().GetProperties()??[];foreach(var p in properties)table.Columns.Add(p.Name,Nullable.GetUnderlyingType(p.PropertyType)??p.PropertyType);for(var i=0;i<pageRows.Count;i++){var row=table.NewRow();row["No"]=(currentPage-1)*PageSize+i+1;foreach(var p in properties)row[p.Name]=p.GetValue(pageRows[i])??DBNull.Value;table.Rows.Add(row);}grid.DataSource=table;foreach(DataGridViewColumn column in grid.Columns)if(column.Name.Equals("Id",StringComparison.OrdinalIgnoreCase)||column.Name.EndsWith("Id",StringComparison.OrdinalIgnoreCase))column.Visible=false;if(grid.Columns.Contains("No")){grid.Columns["No"].FillWeight=12;grid.Columns["No"].MinimumWidth=55;}pageLabel.Text=$"Page {currentPage} of {pages}   •   {filtered.Count} records";}
    async Task AddAsync(){switch(mode){case "Teachers":using(var d=new TeacherDialog()){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.CreateTeacherAsync(d.Username,d.Password,d.Code,d.FullName,d.Phone);}break;case "Rooms":using(var d=new RoomDialog(await s.Admin.GetTeachersAsync())){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveRoomAsync(null,d.RoomName,d.Department,d.Program,d.StudyLevel,d.Semester,d.Year,d.TeacherId,true);}break;case "Subjects":using(var d=new SubjectDialog()){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveSubjectAsync(null,d.SubjectName,d.Code,true);}break;case "Timetables":using(var d=new TimetableDialog(await s.Admin.GetTeachersAsync(),await s.Admin.GetRoomsAsync(),await s.Admin.GetSubjectsAsync())){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveTimetableAsync(d.TeacherId,d.RoomId,d.SubjectId,d.DayOfWeek,d.StartTime,d.EndTime,d.EffectiveFrom,d.EffectiveTo);}break;default:using(var d=new AssignmentDialog(await s.Admin.GetTeachersAsync(),await s.Admin.GetRoomsAsync(),await s.Admin.GetSubjectsAsync())){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveAssignmentAsync(d.TeacherId,d.RoomId,d.SubjectId);}break;}await LoadAsync();}
    async Task EditAsync(){if(grid.CurrentRow is null)throw new InvalidOperationException("Select a row first.");if(mode!="Teachers")throw new InvalidOperationException("Editing is currently available for lecturer details. Other records can be deactivated and recreated safely.");var id=Convert.ToInt32(grid.CurrentRow.Cells["Id"].Value);var code=Convert.ToString(grid.CurrentRow.Cells["Code"].Value)??"";var name=Convert.ToString(grid.CurrentRow.Cells["Name"].Value)??"";var phone=Convert.ToString(grid.CurrentRow.Cells["Phone"].Value)??"";using var d=new EditTeacherDialog(code,name,phone);if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.UpdateTeacherAsync(id,d.Code,d.FullName,d.Phone);await LoadAsync();}
    async Task ToggleActiveAsync(){if(grid.CurrentRow is null)throw new InvalidOperationException("Select a row first.");if(mode is not ("Teachers" or "Timetables"))throw new InvalidOperationException("Status changes are available for lecturers and timetable sessions.");var id=Convert.ToInt32(grid.CurrentRow.Cells["Id"].Value);var active=Convert.ToBoolean(grid.CurrentRow.Cells["Active"].Value);var action=active?"deactivate":"activate";if(MessageBox.Show($"Do you want to {action} this {DisplayEntity}?",$"Confirm {action}",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;if(mode=="Teachers")await s.Admin.SetTeacherActiveAsync(id,!active);else await s.Admin.SetTimetableActiveAsync(id,!active);await LoadAsync();}
    void StatusFormatting(object? sender,DataGridViewCellFormattingEventArgs e){if(e.RowIndex<0||grid.Columns[e.ColumnIndex].Name!="Active"||e.Value is not bool active)return;e.CellStyle!.BackColor=active?Color.FromArgb(229,247,240):Color.FromArgb(255,235,235);e.CellStyle.SelectionBackColor=e.CellStyle.BackColor;}
    abstract class EntryDialog:Form{protected readonly FlowLayoutPanel P=new(){Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(28),BackColor=Color.White};protected TextBox Field(string label,bool password=false){var t=new TextBox{Width=320,UseSystemPasswordChar=password};P.Controls.Add(Ui.Label(label));P.Controls.Add(t);return t;}protected ComboBox Choice(string label,object data){var c=new ComboBox{Width=320,DropDownStyle=ComboBoxStyle.DropDownList,DataSource=data};P.Controls.Add(Ui.Label(label));P.Controls.Add(c);return c;}protected EntryDialog(string title,int h=500){Ui.Configure(this,title);Text=title;Size=new Size(430,h);MinimumSize=Size;MaximizeBox=false;StartPosition=FormStartPosition.CenterParent;Controls.Add(P);}protected void Finish(){var b=Ui.Button("Save",(_,_)=>DialogResult=DialogResult.OK);b.Width=320;P.Controls.Add(b);AcceptButton=b;Ui.ThemeContainer(this);}}
    sealed class TeacherDialog:EntryDialog{readonly TextBox u,p,c,n,ph;public string Username=>u.Text;public string Password=>p.Text;public string Code=>c.Text;public string FullName=>n.Text;public string Phone=>ph.Text;public TeacherDialog():base("Create Teacher",580){u=Field("Username");p=Field("Temporary password (8+ characters)",true);c=Field("Teacher code");n=Field("Full name");ph=Field("Phone");Finish();}}
    sealed class EditTeacherDialog:EntryDialog{readonly TextBox c,n,ph;public string Code=>c.Text;public string FullName=>n.Text;public string Phone=>ph.Text;public EditTeacherDialog(string code,string name,string phone):base("Edit Lecturer",430){c=Field("Lecturer code");c.Text=code;n=Field("Full name");n.Text=name;ph=Field("Phone");ph.Text=phone;Finish();}}
    sealed class RoomDialog:EntryDialog{readonly TextBox n,d,p,l,y;readonly ComboBox sem,t;public string RoomName=>n.Text;public string Department=>d.Text;public string Program=>p.Text;public string StudyLevel=>l.Text;public int Semester=>(int)(sem.SelectedItem??1);public string Year=>y.Text;public int? TeacherId=>(t.SelectedItem as LookupItem)?.Id;public RoomDialog(object teachers):base("Create University Class",720){n=Field("Class / section name (for example: CS-1A)");d=Field("Department (for example: Computing)");p=Field("Program (for example: B.Sc. Computer Science)");l=Field("Study level (for example: Year 1 to Year 5)");sem=Choice("Semester (1-10)",Enumerable.Range(1,10).ToArray());y=Field("Academic year (for example: 2026-2027)");t=Choice("Academic advisor / home-room teacher",teachers);Finish();}}
    sealed class SubjectDialog:EntryDialog{readonly TextBox n,c;public string SubjectName=>n.Text;public string Code=>c.Text;public SubjectDialog():base("Create Subject",350){n=Field("Subject name");c=Field("Subject code");Finish();}}
    sealed class AssignmentDialog:EntryDialog{readonly ComboBox t,r,su;public int TeacherId=>((LookupItem)t.SelectedItem!).Id;public int RoomId=>((LookupItem)r.SelectedItem!).Id;public int SubjectId=>((LookupItem)su.SelectedItem!).Id;public AssignmentDialog(object teachers,object rooms,object subjects):base("Assign Lecturer",440){t=Choice("Lecturer",teachers);r=Choice("University class",rooms);su=Choice("Course / subject",subjects);Finish();}}
    sealed class TimetableDialog:Form
    {
        readonly ComboBox t=new(){DropDownStyle=ComboBoxStyle.DropDownList},r=new(){DropDownStyle=ComboBoxStyle.DropDownList},su=new(){DropDownStyle=ComboBoxStyle.DropDownList},day=new(){DropDownStyle=ComboBoxStyle.DropDownList};
        readonly DateTimePicker start=new(){Format=DateTimePickerFormat.Time,ShowUpDown=true},end=new(){Format=DateTimePickerFormat.Time,ShowUpDown=true},from=new(){Format=DateTimePickerFormat.Short},to=new(){Format=DateTimePickerFormat.Short};
        public int TeacherId=>((LookupItem)t.SelectedItem!).Id;public int RoomId=>((LookupItem)r.SelectedItem!).Id;public int SubjectId=>((LookupItem)su.SelectedItem!).Id;public int DayOfWeek=>day.SelectedIndex+1;public TimeSpan StartTime=>start.Value.TimeOfDay;public TimeSpan EndTime=>end.Value.TimeOfDay;public DateTime EffectiveFrom=>from.Value.Date;public DateTime EffectiveTo=>to.Value.Date;
        public TimetableDialog(object teachers,object rooms,object subjects)
        {
            Ui.Configure(this,"Add Timetable Session");Size=new Size(780,500);MinimumSize=Size;MaximizeBox=false;StartPosition=FormStartPosition.CenterParent;t.DataSource=teachers;r.DataSource=rooms;su.DataSource=subjects;day.DataSource=new[]{"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};start.Value=DateTime.Today.AddHours(9);end.Value=DateTime.Today.AddHours(10);to.Value=DateTime.Today.AddMonths(5);
            var heading=new Label{Text="Schedule a class session",Dock=DockStyle.Top,Height=58,Font=new Font("Segoe UI Semibold",18),ForeColor=Ui.Text,Padding=new Padding(24,15,0,0)};
            var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=4,Padding=new Padding(18),BackColor=Ui.Surface};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));for(var i=0;i<4;i++)layout.RowStyles.Add(new RowStyle(SizeType.Percent,25));
            layout.Controls.Add(Field("Lecturer",t),0,0);layout.Controls.Add(Field("University class",r),1,0);layout.Controls.Add(Field("Course",su),0,1);layout.Controls.Add(Field("Weekday",day),1,1);layout.Controls.Add(Field("Start time",start),0,2);layout.Controls.Add(Field("End time",end),1,2);layout.Controls.Add(Field("Effective from",from),0,3);layout.Controls.Add(Field("Effective to",to),1,3);
            var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=68,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(12),BackColor=Ui.Surface};var save=Ui.Button("Save session",(_,_)=>DialogResult=DialogResult.OK);var cancel=Ui.SecondaryButton("Cancel",(_,_)=>DialogResult=DialogResult.Cancel);actions.Controls.Add(save);actions.Controls.Add(cancel);Controls.Add(layout);Controls.Add(actions);Controls.Add(heading);AcceptButton=save;CancelButton=cancel;Ui.ThemeContainer(this);
        }
        static Panel Field(string label,Control input){var panel=new Panel{Dock=DockStyle.Fill,Padding=new Padding(10)};var caption=Ui.Label(label);caption.Dock=DockStyle.Top;caption.Height=27;input.Dock=DockStyle.Top;input.Height=34;panel.Controls.Add(input);panel.Controls.Add(caption);return panel;}
    }
}
