using Microsoft.Data.SqlClient;
using System.Data;
using StudentAttendanceSystem.Forms.Shared;
using StudentAttendanceSystem.Models;
using StudentAttendanceSystem.Services;

namespace StudentAttendanceSystem.Forms.Admin;

public sealed class AdminManagementControl:UserControl
{
    readonly AppServices s;readonly string mode;readonly DataGridView grid=new(){Dock=DockStyle.Fill};readonly TextBox search=new(){Width=210,PlaceholderText="Search this list..."};readonly ComboBox classFilter=new(){Width=220,DropDownStyle=ComboBoxStyle.DropDownList},yearFilter=new(){Width=150,DropDownStyle=ComboBoxStyle.DropDownList};readonly Label pageLabel=new(){AutoSize=true,Margin=new Padding(12,12,12,0),ForeColor=Ui.Muted};object? loadedData;int currentPage=1;const int PageSize=10;
    public AdminManagementControl(AppServices s,string mode)
    {
        this.s=s;this.mode=mode;Ui.ConfigureGrid(grid);
        var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=68,Padding=new Padding(8)};
        if(mode=="Timetables"){bar.Controls.Add(Ui.Label("Class"));bar.Controls.Add(classFilter);}
        if(mode=="Subjects"){yearFilter.DataSource=YearChoices(true);bar.Controls.Add(Ui.Label("Year"));bar.Controls.Add(yearFilter);}
        bar.Controls.AddRange([Ui.Label("Search"),search,Ui.Button($"Add {DisplayEntity}",(_,_)=>Ui.Safe(AddAsync)),Ui.SecondaryButton($"Edit {DisplayEntity}",(_,_)=>Ui.Safe(EditAsync)),Ui.SecondaryButton("Activate / deactivate",(_,_)=>Ui.Safe(ToggleActiveAsync)),Ui.SecondaryButton("Refresh",(_,_)=>Ui.Safe(LoadAsync))]);
        var pager=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(10,5,18,5),BackColor=Ui.Surface};pager.Controls.Add(Ui.SecondaryButton("Next",(_,_)=>{currentPage++;ApplySearch();}));pager.Controls.Add(pageLabel);pager.Controls.Add(Ui.SecondaryButton("Previous",(_,_)=>{if(currentPage>1)currentPage--;ApplySearch();}));
        search.TextChanged+=(_,_)=>{currentPage=1;ApplySearch();};classFilter.SelectedIndexChanged+=(_,_)=>{currentPage=1;ApplySearch();};yearFilter.SelectedIndexChanged+=(_,_)=>{currentPage=1;ApplySearch();};
        Controls.Add(grid);Controls.Add(pager);Controls.Add(bar);Load+=(_,_)=>Ui.Safe(LoadAsync);grid.CellFormatting+=StatusFormatting;
    }
    string DisplayEntity=>mode switch{"Teachers"=>"lecturer","Rooms"=>"class","Subjects"=>"course","Timetables"=>"timetable session",_=>"assignment"};
    static List<LookupItem> YearChoices(bool includeAll=false){var names=new[]{"First Year","Second Year","Third Year","Fourth Year","Fifth Year"};var years=names.Select((name,index)=>new LookupItem(index+1,name)).ToList();if(includeAll)years.Insert(0,new LookupItem(0,"All courses"));return years;}
    async Task LoadAsync(){if(mode=="Timetables"&&classFilter.DataSource is null){var classes=await s.Admin.GetRoomsAsync(false);classes.Insert(0,new LookupItem(0,"All classes"));classFilter.DataSource=classes;}loadedData=mode switch{ "Teachers"=>await s.Db.QueryAsync("SELECT t.TeacherId,t.TeacherCode,t.FullName,t.Phone,u.Username,u.IsActive FROM Teachers t JOIN Users u ON u.UserId=t.UserId ORDER BY t.FullName",r=>new{Id=r.GetInt32(0),Code=r.GetString(1),Name=r.GetString(2),Phone=r.IsDBNull(3)?"":r.GetString(3),Username=r.GetString(4),Active=r.GetBoolean(5)}),"Rooms"=>await s.Db.QueryAsync("SELECT r.RoomId,r.RoomName,r.Department,r.ProgramName,r.StudyLevel,r.Semester,r.AcademicYear,r.HomeRoomTeacherId,COALESCE(t.FullName,'') HomeRoomTeacher,r.IsActive FROM Rooms r LEFT JOIN Teachers t ON t.TeacherId=r.HomeRoomTeacherId ORDER BY r.ProgramName,r.StudyLevel,r.RoomName",r=>new{Id=r.GetInt32(0),ClassSection=r.GetString(1),Department=r.GetString(2),Program=r.GetString(3),Year=r.GetString(4),Semester=r.GetByte(5),AcademicYear=r.GetString(6),HomeTeacherId=r.IsDBNull(7)?(int?)null:r.GetInt32(7),HomeTeacher=r.GetString(8),Active=r.GetBoolean(9)}),"Subjects"=>await s.Db.QueryAsync("SELECT SubjectId,SubjectCode,SubjectName,CourseYear,IsActive FROM Subjects ORDER BY CourseYear,SubjectName",r=>new{Id=r.GetInt32(0),Code=r.GetString(1),Name=r.GetString(2),Year=r.GetByte(3),Active=r.GetBoolean(4)}),"Timetables"=>await s.Db.QueryAsync("SELECT tt.TimetableId,tt.RoomId,tt.SubjectId,tt.TeacherId,r.RoomName,s.SubjectCode+' - '+s.SubjectName,t.FullName,tt.DayOfWeek,CHOOSE(tt.DayOfWeek,'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'),tt.StartTime,tt.EndTime,tt.EffectiveFrom,tt.EffectiveTo,tt.IsActive FROM Timetables tt JOIN Rooms r ON r.RoomId=tt.RoomId JOIN Subjects s ON s.SubjectId=tt.SubjectId JOIN Teachers t ON t.TeacherId=tt.TeacherId ORDER BY tt.DayOfWeek,tt.StartTime",r=>new{Id=r.GetInt32(0),RoomId=r.GetInt32(1),SubjectId=r.GetInt32(2),TeacherId=r.GetInt32(3),Class=r.GetString(4),Course=r.GetString(5),Lecturer=r.GetString(6),DayNumber=r.GetByte(7),Day=r.GetString(8),Start=r.GetTimeSpan(9).ToString(@"hh\:mm"),End=r.GetTimeSpan(10).ToString(@"hh\:mm"),FromDate=r.GetDateTime(11),ToDate=r.GetDateTime(12),From=r.GetDateTime(11).ToShortDateString(),To=r.GetDateTime(12).ToShortDateString(),Active=r.GetBoolean(13)}),_=>await s.Db.QueryAsync("SELECT ta.AssignmentId,ta.TeacherId,ta.RoomId,ta.SubjectId,t.FullName Teacher,r.RoomName Room,s.SubjectName Subject,ta.AcademicYear,ta.IsActive FROM TeacherAssignments ta JOIN Teachers t ON t.TeacherId=ta.TeacherId JOIN Rooms r ON r.RoomId=ta.RoomId JOIN Subjects s ON s.SubjectId=ta.SubjectId ORDER BY t.FullName,r.RoomName,s.SubjectName",r=>new{Id=r.GetInt32(0),TeacherId=r.GetInt32(1),RoomId=r.GetInt32(2),SubjectId=r.GetInt32(3),Teacher=r.GetString(4),Room=r.GetString(5),Subject=r.GetString(6),Year=r.GetString(7),Active=r.GetBoolean(8)})};ApplySearch();}
    void ApplySearch(){if(loadedData is not System.Collections.IEnumerable rows)return;var q=search.Text.Trim();var filtered=new List<object>();foreach(var x in rows)if(x is not null&&(classFilter.SelectedItem is not LookupItem selectedClass||selectedClass.Id==0||Convert.ToInt32(x.GetType().GetProperty("RoomId")?.GetValue(x)??0)==selectedClass.Id)&&(yearFilter.SelectedItem is not LookupItem selectedYear||selectedYear.Id==0||Convert.ToInt32(x.GetType().GetProperty("Year")?.GetValue(x)??0)==selectedYear.Id)&&(string.IsNullOrEmpty(q)||x.GetType().GetProperties().Any(p=>p.GetValue(x)?.ToString()?.Contains(q,StringComparison.OrdinalIgnoreCase)==true)))filtered.Add(x);filtered=filtered.OrderBy(x=>Convert.ToInt32(x.GetType().GetProperty("Id")?.GetValue(x)??0)).ToList();var pages=Math.Max(1,(int)Math.Ceiling(filtered.Count/(double)PageSize));currentPage=Math.Clamp(currentPage,1,pages);var pageRows=filtered.Skip((currentPage-1)*PageSize).Take(PageSize).ToList();var table=new DataTable();table.Columns.Add("No",typeof(int));var properties=filtered.FirstOrDefault()?.GetType().GetProperties()??[];foreach(var p in properties)table.Columns.Add(p.Name,Nullable.GetUnderlyingType(p.PropertyType)??p.PropertyType);for(var i=0;i<pageRows.Count;i++){var row=table.NewRow();row["No"]=(currentPage-1)*PageSize+i+1;foreach(var p in properties)row[p.Name]=p.GetValue(pageRows[i])??DBNull.Value;table.Rows.Add(row);}grid.DataSource=table;foreach(DataGridViewColumn column in grid.Columns)if(column.Name.Equals("Id",StringComparison.OrdinalIgnoreCase)||column.Name.EndsWith("Id",StringComparison.OrdinalIgnoreCase)||column.Name is "DayNumber" or "FromDate" or "ToDate")column.Visible=false;if(grid.Columns.Contains("No")){grid.Columns["No"].FillWeight=12;grid.Columns["No"].MinimumWidth=55;}pageLabel.Text=$"Page {currentPage} of {pages}   •   {filtered.Count} records";}
    async Task AddAsync(){switch(mode){case "Teachers":using(var d=new TeacherDialog()){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.CreateTeacherAsync(d.Username,d.Password,d.Code,d.FullName,d.Phone);}break;case "Rooms":using(var d=new RoomDialog(await s.Admin.GetTeachersAsync())){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveRoomAsync(null,d.RoomName,d.Department,d.Program,d.ClassYear,d.Semester,d.Year,d.TeacherId,true);}break;case "Subjects":using(var d=new SubjectDialog()){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveSubjectAsync(null,d.SubjectName,d.Code,d.CourseYear,true);}break;case "Timetables":using(var d=new TimetableDialog(s.Admin,await s.Admin.GetRoomsAsync())){await d.InitializeAsync();if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveTimetableAsync(d.TeacherId,d.RoomId,d.SubjectId,d.DayOfWeek,d.StartTime,d.EndTime,d.EffectiveFrom,d.EffectiveTo);}break;default:using(var d=new AssignmentDialog(s.Admin,await s.Admin.GetTeachersAsync(),await s.Admin.GetRoomsAsync())){await d.InitializeAsync();if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveAssignmentAsync(d.TeacherId,d.RoomId,d.SubjectId);}break;}await LoadAsync();}
    async Task EditAsync()
    {
        if(grid.CurrentRow is null)throw new InvalidOperationException("Select a row first.");
        var row=grid.CurrentRow;var id=Convert.ToInt32(row.Cells["Id"].Value);
        switch(mode)
        {
            case "Teachers": using(var d=new EditTeacherDialog(Cell("Code"),Cell("Name"),Cell("Phone"))){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.UpdateTeacherAsync(id,d.Code,d.FullName,d.Phone);} break;
            case "Rooms": using(var d=new RoomDialog(await s.Admin.GetTeachersAsync(false),Cell("ClassSection"),Cell("Department"),Cell("Program"),Cell("Year"),Convert.ToInt32(row.Cells["Semester"].Value),Cell("AcademicYear"),NullableId("HomeTeacherId"),"Edit University Class")){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveRoomAsync(id,d.RoomName,d.Department,d.Program,d.ClassYear,d.Semester,d.Year,d.TeacherId,Convert.ToBoolean(row.Cells["Active"].Value));} break;
            case "Subjects": using(var d=new SubjectDialog(Cell("Name"),Cell("Code"),Convert.ToInt32(row.Cells["Year"].Value),"Edit Course")){if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveSubjectAsync(id,d.SubjectName,d.Code,d.CourseYear,Convert.ToBoolean(row.Cells["Active"].Value));} break;
            case "Assignments": using(var d=new AssignmentDialog(s.Admin,await s.Admin.GetTeachersAsync(false),await s.Admin.GetRoomsAsync(false),Convert.ToInt32(row.Cells["TeacherId"].Value),Convert.ToInt32(row.Cells["RoomId"].Value),Convert.ToInt32(row.Cells["SubjectId"].Value),"Edit Lecturer Assignment")){await d.InitializeAsync();if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveAssignmentAsync(d.TeacherId,d.RoomId,d.SubjectId,id);} break;
            case "Timetables": using(var d=new TimetableDialog(s.Admin,await s.Admin.GetRoomsAsync(false),Convert.ToInt32(row.Cells["TeacherId"].Value),Convert.ToInt32(row.Cells["RoomId"].Value),Convert.ToInt32(row.Cells["SubjectId"].Value),Convert.ToInt32(row.Cells["DayNumber"].Value),TimeSpan.Parse(Cell("Start")),TimeSpan.Parse(Cell("End")),Convert.ToDateTime(row.Cells["FromDate"].Value),Convert.ToDateTime(row.Cells["ToDate"].Value))){await d.InitializeAsync();if(d.ShowDialog()!=DialogResult.OK)return;await s.Admin.SaveTimetableAsync(d.TeacherId,d.RoomId,d.SubjectId,d.DayOfWeek,d.StartTime,d.EndTime,d.EffectiveFrom,d.EffectiveTo,id);} break;
        }
        await LoadAsync();
        string Cell(string name)=>Convert.ToString(row.Cells[name].Value)??"";
        int? NullableId(string name)=>row.Cells[name].Value is DBNull?null:Convert.ToInt32(row.Cells[name].Value);
    }
    async Task ToggleActiveAsync()
    {
        if(grid.CurrentRow is null)throw new InvalidOperationException("Select a row first.");
        var id=Convert.ToInt32(grid.CurrentRow.Cells["Id"].Value);var active=Convert.ToBoolean(grid.CurrentRow.Cells["Active"].Value);var action=active?"deactivate":"activate";
        if(MessageBox.Show($"Do you want to {action} this {DisplayEntity}?",$"Confirm {action}",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;
        switch(mode)
        {
            case "Teachers": await s.Admin.SetTeacherActiveAsync(id,!active); break;
            case "Rooms": await s.Admin.SetRoomActiveAsync(id,!active); break;
            case "Subjects": await s.Admin.SetSubjectActiveAsync(id,!active); break;
            case "Assignments": await s.Admin.SetAssignmentActiveAsync(id,!active); break;
            case "Timetables": await s.Admin.SetTimetableActiveAsync(id,!active); break;
        }
        await LoadAsync();
    }
    void StatusFormatting(object? sender,DataGridViewCellFormattingEventArgs e){if(e.RowIndex<0||grid.Columns[e.ColumnIndex].Name!="Active"||e.Value is not bool active)return;e.CellStyle!.BackColor=active?Color.FromArgb(229,247,240):Color.FromArgb(255,235,235);e.CellStyle.SelectionBackColor=e.CellStyle.BackColor;}
    abstract class EntryDialog:Form{protected readonly FlowLayoutPanel P=new(){Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(28),BackColor=Color.White};protected TextBox Field(string label,bool password=false){var t=new TextBox{Width=320,UseSystemPasswordChar=password};P.Controls.Add(Ui.Label(label));P.Controls.Add(t);return t;}protected ComboBox Choice(string label,object data){var c=new ComboBox{Width=320,DropDownStyle=ComboBoxStyle.DropDownList,DataSource=data};P.Controls.Add(Ui.Label(label));P.Controls.Add(c);return c;}protected EntryDialog(string title,int h=500){Ui.Configure(this,title);Text=title;Size=new Size(430,h);MinimumSize=Size;MaximizeBox=false;StartPosition=FormStartPosition.CenterParent;Controls.Add(P);}protected void Finish(){var b=Ui.Button("Save",(_,_)=>DialogResult=DialogResult.OK);b.Width=320;P.Controls.Add(b);AcceptButton=b;Ui.ThemeContainer(this);}}
    sealed class TeacherDialog:EntryDialog{readonly TextBox u,p,c,n,ph;public string Username=>u.Text;public string Password=>p.Text;public string Code=>c.Text;public string FullName=>n.Text;public string Phone=>ph.Text;public TeacherDialog():base("Create Teacher",580){u=Field("Username");p=Field("Temporary password (8+ characters)",true);c=Field("Teacher code");n=Field("Full name");ph=Field("Phone");Finish();}}
    sealed class EditTeacherDialog:EntryDialog{readonly TextBox c,n,ph;public string Code=>c.Text;public string FullName=>n.Text;public string Phone=>ph.Text;public EditTeacherDialog(string code,string name,string phone):base("Edit Lecturer",430){c=Field("Lecturer code");c.Text=code;n=Field("Full name");n.Text=name;ph=Field("Phone");ph.Text=phone;Finish();}}
    sealed class RoomDialog:EntryDialog{readonly TextBox n,d,p,l,y;readonly ComboBox sem,t;public string RoomName=>n.Text;public string Department=>d.Text;public string Program=>p.Text;public string ClassYear=>l.Text;public int Semester=>(int)(sem.SelectedItem??1);public string Year=>y.Text;public int? TeacherId=>(t.SelectedItem as LookupItem)?.Id;public RoomDialog(object teachers,string name="",string department="",string program="",string level="",int semester=1,string year="",int? teacherId=null,string title="Create University Class"):base(title,720){n=Field("Class / section name (for example: CS-1A)");n.Text=name;d=Field("Department (for example: Computing)");d.Text=department;p=Field("Program (for example: B.Sc. Computer Science)");p.Text=program;l=Field("Year (for example: Year 1 to Year 5)");l.Text=level;sem=Choice("Semester (1-10)",Enumerable.Range(1,10).ToArray());sem.SelectedItem=semester;y=Field("Academic year (for example: 2026-2027)");y.Text=year;t=Choice("Academic advisor / home-room teacher",teachers);SelectLookup(t,teacherId);Finish();}}
    sealed class SubjectDialog:EntryDialog{readonly TextBox n,c;readonly ComboBox y;public string SubjectName=>n.Text;public string Code=>c.Text;public int CourseYear=>((LookupItem)y.SelectedItem!).Id;public SubjectDialog(string name="",string code="",int courseYear=1,string title="Create Course"):base(title,430){n=Field("Course name");n.Text=name;c=Field("Course code");c.Text=code;y=Choice("University year",YearChoices());SelectLookup(y,courseYear);Finish();}}
    sealed class AssignmentDialog:EntryDialog
    {
        readonly AdminService admin;readonly int? preferredSubjectId;readonly ComboBox t,r,su;
        public int TeacherId=>((LookupItem)t.SelectedItem!).Id;public int RoomId=>((LookupItem)r.SelectedItem!).Id;public int SubjectId=>((LookupItem)su.SelectedItem!).Id;
        public AssignmentDialog(AdminService admin,object teachers,object rooms,int? teacherId=null,int? roomId=null,int? subjectId=null,string title="Assign Lecturer"):base(title,440){this.admin=admin;preferredSubjectId=subjectId;t=Choice("Lecturer",teachers);r=Choice("University class",rooms);su=Choice("Course for selected class year",new List<LookupItem>());SelectLookup(t,teacherId);SelectLookup(r,roomId);r.SelectedIndexChanged+=(_,_)=>Ui.Safe(LoadCoursesAsync);Finish();}
        public Task InitializeAsync()=>LoadCoursesAsync();
        async Task LoadCoursesAsync(){if(r.SelectedItem is not LookupItem room)return;var selected=(su.SelectedItem as LookupItem)?.Id??preferredSubjectId;su.DataSource=await admin.GetSubjectsForRoomAsync(room.Id,false);SelectLookup(su,selected);}
    }
    static void SelectLookup(ComboBox combo,int? id){if(id is null)return;for(var i=0;i<combo.Items.Count;i++)if(combo.Items[i] is LookupItem item&&item.Id==id){combo.SelectedIndex=i;return;}}
    sealed class TimetableDialog:Form
    {
        readonly AdminService admin;readonly int? preferredTeacherId,preferredSubjectId;
        readonly ComboBox t=new(){DropDownStyle=ComboBoxStyle.DropDownList},r=new(){DropDownStyle=ComboBoxStyle.DropDownList},su=new(){DropDownStyle=ComboBoxStyle.DropDownList},day=new(){DropDownStyle=ComboBoxStyle.DropDownList};
        readonly DateTimePicker start=new(){Format=DateTimePickerFormat.Time,ShowUpDown=true},end=new(){Format=DateTimePickerFormat.Time,ShowUpDown=true},from=new(){Format=DateTimePickerFormat.Short},to=new(){Format=DateTimePickerFormat.Short};
        public int TeacherId=>((LookupItem)t.SelectedItem!).Id;public int RoomId=>((LookupItem)r.SelectedItem!).Id;public int SubjectId=>((LookupItem)su.SelectedItem!).Id;public int DayOfWeek=>day.SelectedIndex+1;public TimeSpan StartTime=>start.Value.TimeOfDay;public TimeSpan EndTime=>end.Value.TimeOfDay;public DateTime EffectiveFrom=>from.Value.Date;public DateTime EffectiveTo=>to.Value.Date;
        public TimetableDialog(AdminService admin,object rooms,int? teacherId=null,int? roomId=null,int? subjectId=null,int dayNumber=1,TimeSpan? startTime=null,TimeSpan? endTime=null,DateTime? fromDate=null,DateTime? toDate=null)
        {
            this.admin=admin;preferredTeacherId=teacherId;preferredSubjectId=subjectId;Ui.Configure(this,teacherId is null?"Add Timetable Session":"Edit Timetable Session");Size=new Size(780,500);MinimumSize=Size;MaximizeBox=false;StartPosition=FormStartPosition.CenterParent;r.DataSource=rooms;su.DataSource=new List<LookupItem>();day.Items.AddRange(new object[]{"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"});SelectLookup(r,roomId);day.SelectedIndex=Math.Clamp(dayNumber-1,0,6);start.Value=DateTime.Today+(startTime??TimeSpan.FromHours(9));end.Value=DateTime.Today+(endTime??TimeSpan.FromHours(10));from.Value=fromDate??DateTime.Today;to.Value=toDate??DateTime.Today.AddMonths(5);
            var heading=new Label{Text="Schedule a class session",Dock=DockStyle.Top,Height=58,Font=new Font("Segoe UI Semibold",18),ForeColor=Ui.Text,Padding=new Padding(24,15,0,0)};
            var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=4,Padding=new Padding(18),BackColor=Ui.Surface};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));for(var i=0;i<4;i++)layout.RowStyles.Add(new RowStyle(SizeType.Percent,25));
            layout.Controls.Add(Field("Assigned lecturer",t),0,0);layout.Controls.Add(Field("University class",r),1,0);layout.Controls.Add(Field("Course",su),0,1);layout.Controls.Add(Field("Weekday",day),1,1);layout.Controls.Add(Field("Start time",start),0,2);layout.Controls.Add(Field("End time",end),1,2);layout.Controls.Add(Field("Effective from",from),0,3);layout.Controls.Add(Field("Effective to",to),1,3);
            var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=68,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(12),BackColor=Ui.Surface};var save=Ui.Button("Save session",(_,_)=>{if(t.SelectedItem is not LookupItem){MessageBox.Show("Assign an active lecturer to this class and course first.","Lecturer assignment required",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}DialogResult=DialogResult.OK;});var cancel=Ui.SecondaryButton("Cancel",(_,_)=>DialogResult=DialogResult.Cancel);actions.Controls.Add(save);actions.Controls.Add(cancel);Controls.Add(layout);Controls.Add(actions);Controls.Add(heading);AcceptButton=save;CancelButton=cancel;Ui.ThemeContainer(this);
            r.SelectedIndexChanged+=(_,_)=>Ui.Safe(LoadCoursesAsync);su.SelectedIndexChanged+=(_,_)=>Ui.Safe(LoadAssignedTeachersAsync);
        }
        public Task InitializeAsync()=>LoadCoursesAsync();
        async Task LoadCoursesAsync(){if(r.SelectedItem is not LookupItem room)return;var selected=(su.SelectedItem as LookupItem)?.Id??preferredSubjectId;su.DataSource=await admin.GetSubjectsForRoomAsync(room.Id,preferredSubjectId is null);SelectLookup(su,selected);await LoadAssignedTeachersAsync();}
        async Task LoadAssignedTeachersAsync(){if(r.SelectedItem is not LookupItem room||su.SelectedItem is not LookupItem subject)return;var selected=(t.SelectedItem as LookupItem)?.Id??preferredTeacherId;var teachers=await admin.GetAssignedTeachersAsync(room.Id,subject.Id);t.DataSource=teachers;SelectLookup(t,selected);}
        static Panel Field(string label,Control input){var panel=new Panel{Dock=DockStyle.Fill,Padding=new Padding(10)};var caption=Ui.Label(label);caption.Dock=DockStyle.Top;caption.Height=27;input.Dock=DockStyle.Top;input.Height=34;panel.Controls.Add(input);panel.Controls.Add(caption);return panel;}
    }
}
