using System;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Windows.Forms;
namespace StudentAttendanceSystemVS2012
{
 static class AdminDialogs
 {
  public static void Add(Database db,string table){Show(db,table,null);}public static void Edit(Database db,string table,int id){Show(db,table,id);}
  static void Show(Database db,string table,int? id){Form dialog;if(table=="Users")dialog=new LecturerDialog(db,id);else if(table=="Rooms")dialog=new RoomDialog(db,id);else if(table=="TeacherAssignments")dialog=new AssignmentDialog(db,id);else if(table=="Timetables")dialog=new TimetableDialog(db,id);else return;dialog.ShowDialog();dialog.Dispose();}
 }
 abstract class EntryForm:Form
 {
  protected readonly Database Db;protected readonly int? Id;protected readonly FlowLayoutPanel Body=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(28),BackColor=Color.White};
  protected EntryForm(Database db,int? id,string addTitle,string editTitle,int height){Db=db;Id=id;Text=id.HasValue?editTitle:addTitle;Size=new Size(440,height);StartPosition=FormStartPosition.CenterParent;MaximizeBox=false;Controls.Add(Body);}
  protected TextBox TextField(string label,string value){var x=new TextBox{Width=330,Text=value??""};Body.Controls.Add(Ui.Label(label));Body.Controls.Add(x);return x;}protected ComboBox ListField(string label,DataTable data,string display,string value){var x=new ComboBox{Width=330,DropDownStyle=ComboBoxStyle.DropDownList,DataSource=data,DisplayMember=display,ValueMember=value};Body.Controls.Add(Ui.Label(label));Body.Controls.Add(x);return x;}protected void Select(ComboBox box,object value){if(value!=null&&value!=DBNull.Value)box.SelectedValue=value;}protected void Finish(Action save){var b=Ui.Button("Save",delegate{try{save();DialogResult=DialogResult.OK;}catch(Exception ex){MessageBox.Show(ex.Message,"Unable to complete action",MessageBoxButtons.OK,MessageBoxIcon.Warning);}});b.Width=330;Body.Controls.Add(b);AcceptButton=b;Ui.Style(this);}
 }
 sealed class LecturerDialog:EntryForm
 {
  readonly TextBox username,password,code,name,phone;
  public LecturerDialog(Database db,int? id):base(db,id,"Add Lecturer","Edit Lecturer",590){DataRow row=null;if(id.HasValue)row=Db.Query("SELECT u.Username,t.TeacherCode,t.FullName,t.Phone FROM Users u INNER JOIN Teachers t ON t.UserId=u.UserId WHERE u.UserId=@id",new SqlParameter("@id",id.Value)).Rows[0];username=TextField("Username",row==null?"":Convert.ToString(row["Username"]));username.Enabled=!id.HasValue;password=TextField(id.HasValue?"New password (leave blank to keep current)":"Temporary password","");password.UseSystemPasswordChar=true;code=TextField("Lecturer code",row==null?"":Convert.ToString(row["TeacherCode"]));name=TextField("Full name",row==null?"":Convert.ToString(row["FullName"]));phone=TextField("Phone",row==null?"":Convert.ToString(row["Phone"]));Finish(Save);}
  void Save(){if(code.Text.Trim().Length==0||name.Text.Trim().Length==0)throw new InvalidOperationException("Lecturer code and full name are required.");if(!Id.HasValue){if(username.Text.Trim().Length==0||password.Text.Length<8)throw new InvalidOperationException("Username and a password of at least 8 characters are required.");Db.Execute("BEGIN TRAN; INSERT Users(Username,PasswordHash,FullName,Role,IsActive) VALUES(@u,@p,@n,'Teacher',1); DECLARE @uid int=SCOPE_IDENTITY(); INSERT Teachers(UserId,TeacherCode,FullName,Phone) VALUES(@uid,@c,@n,@ph); COMMIT;",new SqlParameter("@u",username.Text.Trim()),new SqlParameter("@p",PasswordHasher.Hash(password.Text)),new SqlParameter("@n",name.Text.Trim()),new SqlParameter("@c",code.Text.Trim()),new SqlParameter("@ph",phone.Text.Trim()));}else Db.Execute("UPDATE t SET TeacherCode=@c,FullName=@n,Phone=@ph FROM Teachers t WHERE UserId=@id; UPDATE Users SET FullName=@n"+(password.Text.Length>0?",PasswordHash=@p":"")+" WHERE UserId=@id",new SqlParameter("@c",code.Text.Trim()),new SqlParameter("@n",name.Text.Trim()),new SqlParameter("@ph",phone.Text.Trim()),new SqlParameter("@p",password.Text.Length>0?PasswordHasher.Hash(password.Text):""),new SqlParameter("@id",Id.Value));}
 }
 sealed class RoomDialog:EntryForm
 {
  readonly TextBox room,department,program,level,academic;readonly ComboBox semester,teacher;
  public RoomDialog(Database db,int? id):base(db,id,"Add University Class","Edit University Class",700){DataRow row=null;if(id.HasValue)row=Db.Query("SELECT * FROM Rooms WHERE RoomId=@id",new SqlParameter("@id",id.Value)).Rows[0];room=TextField("Class / section",row==null?"":Convert.ToString(row["RoomName"]));department=TextField("Department",row==null?"":Convert.ToString(row["Department"]));program=TextField("Program",row==null?"":Convert.ToString(row["ProgramName"]));level=TextField("Year (First Year to Fifth Year)",row==null?"":Convert.ToString(row["StudyLevel"]));semester=new ComboBox{Width=330,DropDownStyle=ComboBoxStyle.DropDownList};for(var i=1;i<=10;i++)semester.Items.Add(i);semester.SelectedItem=row==null?1:Convert.ToInt32(row["Semester"]);Body.Controls.Add(Ui.Label("Semester"));Body.Controls.Add(semester);academic=TextField("Academic year",row==null?"":Convert.ToString(row["AcademicYear"]));var teachers=Db.Query("SELECT t.TeacherId AS [Id],t.FullName AS [Name] FROM Teachers t INNER JOIN Users u ON u.UserId=t.UserId WHERE u.IsActive=1 OR t.TeacherId=@selected ORDER BY t.FullName",new SqlParameter("@selected",row==null?DBNull.Value:row["HomeRoomTeacherId"]));teacher=ListField("Home-room lecturer",teachers,"Name","Id");if(row!=null)Select(teacher,row["HomeRoomTeacherId"]);Finish(Save);}
  void Save(){if(room.Text.Trim().Length==0)throw new InvalidOperationException("Class name is required.");var args=new[]{new SqlParameter("@r",room.Text.Trim()),new SqlParameter("@d",department.Text.Trim()),new SqlParameter("@p",program.Text.Trim()),new SqlParameter("@l",level.Text.Trim()),new SqlParameter("@s",semester.SelectedItem),new SqlParameter("@y",academic.Text.Trim()),new SqlParameter("@t",teacher.SelectedValue),new SqlParameter("@id",Id)};Db.Execute(Id.HasValue?"UPDATE Rooms SET RoomName=@r,Department=@d,ProgramName=@p,StudyLevel=@l,Semester=@s,AcademicYear=@y,HomeRoomTeacherId=@t WHERE RoomId=@id":"INSERT Rooms(RoomName,Department,ProgramName,StudyLevel,Semester,AcademicYear,HomeRoomTeacherId,IsActive) VALUES(@r,@d,@p,@l,@s,@y,@t,1)",args);}
 }
 sealed class AssignmentDialog:EntryForm
 {
  readonly ComboBox teacher,room,course;
  public AssignmentDialog(Database db,int? id):base(db,id,"Add Lecturer Assignment","Edit Lecturer Assignment",440){DataRow old=null;if(id.HasValue)old=Db.Query("SELECT * FROM TeacherAssignments WHERE AssignmentId=@id",new SqlParameter("@id",id.Value)).Rows[0];teacher=ListField("Lecturer",Db.Query("SELECT t.TeacherId AS [Id],t.FullName AS [Name] FROM Teachers t INNER JOIN Users u ON u.UserId=t.UserId WHERE u.IsActive=1 OR t.TeacherId=@id ORDER BY t.FullName",new SqlParameter("@id",old==null?DBNull.Value:old["TeacherId"])),"Name","Id");room=ListField("University class",Db.Query("SELECT RoomId AS [Id],RoomName AS [Name] FROM Rooms WHERE IsActive=1 OR RoomId=@id ORDER BY RoomName",new SqlParameter("@id",old==null?DBNull.Value:old["RoomId"])),"Name","Id");course=ListField("Course for selected class year",new DataTable(),"Name","Id");room.SelectedValueChanged+=delegate{LoadCourses(old==null?null:(object)old["SubjectId"]);};if(old!=null){Select(teacher,old["TeacherId"]);Select(room,old["RoomId"]);}LoadCourses(old==null?null:(object)old["SubjectId"]);Finish(Save);}
  void LoadCourses(object selected){if(room.SelectedValue==null)return;course.DataSource=Db.Query("SELECT s.SubjectId AS [Id],s.SubjectCode+' - '+s.SubjectName AS [Name] FROM Subjects s INNER JOIN Rooms r ON r.RoomId=@r WHERE s.CourseYear=CASE WHEN r.StudyLevel LIKE '%5%' OR LOWER(r.StudyLevel) LIKE '%fifth%' THEN 5 WHEN r.StudyLevel LIKE '%4%' OR LOWER(r.StudyLevel) LIKE '%fourth%' THEN 4 WHEN r.StudyLevel LIKE '%3%' OR LOWER(r.StudyLevel) LIKE '%third%' THEN 3 WHEN r.StudyLevel LIKE '%2%' OR LOWER(r.StudyLevel) LIKE '%second%' THEN 2 ELSE 1 END ORDER BY s.SubjectCode",new SqlParameter("@r",room.SelectedValue));Select(course,selected);}
  void Save(){Db.Execute("DECLARE @year nvarchar(20)=(SELECT AcademicYear FROM Rooms WHERE RoomId=@r); IF EXISTS(SELECT 1 FROM TeacherAssignments WHERE RoomId=@r AND SubjectId=@s AND AcademicYear=@year AND AssignmentId<>ISNULL(@id,-1)) THROW 51014,'This course has already been assigned to the selected class.',1; IF @id IS NULL INSERT TeacherAssignments(TeacherId,RoomId,SubjectId,AcademicYear,IsActive) VALUES(@t,@r,@s,@year,1); ELSE UPDATE TeacherAssignments SET TeacherId=@t,RoomId=@r,SubjectId=@s,AcademicYear=@year WHERE AssignmentId=@id",new SqlParameter("@t",teacher.SelectedValue),new SqlParameter("@r",room.SelectedValue),new SqlParameter("@s",course.SelectedValue),new SqlParameter("@id",Id));}
 }
 sealed class TimetableDialog:EntryForm
 {
  readonly ComboBox room,course,teacher,day;readonly DateTimePicker start,end,from,to;
  public TimetableDialog(Database db,int? id):base(db,id,"Add Timetable Session","Edit Timetable Session",720){DataRow old=null;if(id.HasValue)old=Db.Query("SELECT * FROM Timetables WHERE TimetableId=@id",new SqlParameter("@id",id.Value)).Rows[0];room=ListField("University class",Db.Query("SELECT RoomId AS [Id],RoomName AS [Name] FROM Rooms WHERE IsActive=1 OR RoomId=@id",new SqlParameter("@id",old==null?DBNull.Value:old["RoomId"])),"Name","Id");course=ListField("Course",new DataTable(),"Name","Id");teacher=ListField("Assigned lecturer",new DataTable(),"Name","Id");day=new ComboBox{Width=330,DropDownStyle=ComboBoxStyle.DropDownList};day.Items.AddRange(new object[]{"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"});Body.Controls.Add(Ui.Label("Weekday"));Body.Controls.Add(day);start=Time("Start time");end=Time("End time");from=Date("Effective from");to=Date("Effective to");room.SelectedValueChanged+=delegate{LoadCourses(old==null?null:(object)old["SubjectId"]);};course.SelectedValueChanged+=delegate{LoadTeachers(old==null?null:(object)old["TeacherId"]);};if(old!=null){Select(room,old["RoomId"]);day.SelectedIndex=Convert.ToInt32(old["DayOfWeek"])-1;start.Value=DateTime.Today+(TimeSpan)old["StartTime"];end.Value=DateTime.Today+(TimeSpan)old["EndTime"];from.Value=Convert.ToDateTime(old["EffectiveFrom"]);to.Value=Convert.ToDateTime(old["EffectiveTo"]);}else{day.SelectedIndex=0;start.Value=DateTime.Today.AddHours(9);end.Value=DateTime.Today.AddHours(10);from.Value=DateTime.Today;to.Value=DateTime.Today.AddMonths(5);}LoadCourses(old==null?null:(object)old["SubjectId"]);Finish(Save);}
  DateTimePicker Time(string label){var x=new DateTimePicker{Width=330,Format=DateTimePickerFormat.Time,ShowUpDown=true};Body.Controls.Add(Ui.Label(label));Body.Controls.Add(x);return x;}DateTimePicker Date(string label){var x=new DateTimePicker{Width=330,Format=DateTimePickerFormat.Short};Body.Controls.Add(Ui.Label(label));Body.Controls.Add(x);return x;}void LoadCourses(object selected){if(room.SelectedValue==null)return;course.DataSource=Db.Query("SELECT s.SubjectId AS [Id],s.SubjectCode+' - '+s.SubjectName AS [Name] FROM Subjects s INNER JOIN Rooms r ON r.RoomId=@r WHERE s.CourseYear=CASE WHEN r.StudyLevel LIKE '%5%' OR LOWER(r.StudyLevel) LIKE '%fifth%' THEN 5 WHEN r.StudyLevel LIKE '%4%' OR LOWER(r.StudyLevel) LIKE '%fourth%' THEN 4 WHEN r.StudyLevel LIKE '%3%' OR LOWER(r.StudyLevel) LIKE '%third%' THEN 3 WHEN r.StudyLevel LIKE '%2%' OR LOWER(r.StudyLevel) LIKE '%second%' THEN 2 ELSE 1 END ORDER BY s.SubjectCode",new SqlParameter("@r",room.SelectedValue));Select(course,selected);}void LoadTeachers(object selected){if(room.SelectedValue==null||course.SelectedValue==null)return;teacher.DataSource=Db.Query("SELECT t.TeacherId AS [Id],t.FullName AS [Name] FROM (TeacherAssignments a INNER JOIN Teachers t ON t.TeacherId=a.TeacherId) INNER JOIN Users u ON u.UserId=t.UserId WHERE a.RoomId=@r AND a.SubjectId=@s AND a.IsActive=1 AND u.IsActive=1",new SqlParameter("@r",room.SelectedValue),new SqlParameter("@s",course.SelectedValue));Select(teacher,selected);}
  void Save(){if(end.Value.TimeOfDay<=start.Value.TimeOfDay)throw new InvalidOperationException("End time must be later than start time.");Db.Execute("DECLARE @ay nvarchar(20),@sem tinyint; SELECT @ay=AcademicYear,@sem=Semester FROM Rooms WHERE RoomId=@r; IF EXISTS(SELECT 1 FROM Timetables WHERE TimetableId<>ISNULL(@id,-1) AND DayOfWeek=@d AND AcademicYear=@ay AND Semester=@sem AND (RoomId=@r OR TeacherId=@t) AND @start<EndTime AND @end>StartTime AND @from<=EffectiveTo AND @to>=EffectiveFrom) THROW 51012,'This time is already taken by the selected class or lecturer.',1; IF @id IS NULL INSERT Timetables(RoomId,SubjectId,TeacherId,DayOfWeek,StartTime,EndTime,AcademicYear,Semester,EffectiveFrom,EffectiveTo,IsActive) VALUES(@r,@s,@t,@d,@start,@end,@ay,@sem,@from,@to,1); ELSE UPDATE Timetables SET RoomId=@r,SubjectId=@s,TeacherId=@t,DayOfWeek=@d,StartTime=@start,EndTime=@end,AcademicYear=@ay,Semester=@sem,EffectiveFrom=@from,EffectiveTo=@to WHERE TimetableId=@id",new SqlParameter("@r",room.SelectedValue),new SqlParameter("@s",course.SelectedValue),new SqlParameter("@t",teacher.SelectedValue),new SqlParameter("@d",day.SelectedIndex+1),new SqlParameter("@start",start.Value.TimeOfDay),new SqlParameter("@end",end.Value.TimeOfDay),new SqlParameter("@from",from.Value.Date),new SqlParameter("@to",to.Value.Date),new SqlParameter("@id",Id));}
 }
}




