using System.Net.Http.Json;
using Attendly.Application;
using Attendly.Domain;
namespace Attendly.WinForms;
public sealed class MainForm:Form
{
    readonly HttpClient api=new(){BaseAddress=new Uri("https://localhost:7049")};readonly TextBox username=new(){PlaceholderText="Username",Width=180},password=new(){PlaceholderText="Password",UseSystemPasswordChar=true,Width=180},room=new(){PlaceholderText="Room ID",Width=90};readonly Label status=new(){AutoSize=true,Margin=new Padding(8,12,0,0)};readonly DataGridView grid=new(){Dock=DockStyle.Fill,ReadOnly=true,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill};int page=1;
    public MainForm(){Text="Attendly Unified - Desktop";Size=new(1100,700);MinimumSize=new(900,600);BackColor=Color.FromArgb(246,247,251);var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=70,Padding=new Padding(12),BackColor=Color.White};var login=MakeButton("Sign in");login.Click+=async(_,_)=>await LoginAsync();var load=MakeButton("Load students");load.Click+=async(_,_)=>{page=1;await LoadStudentsAsync();};var previous=MakeButton("Previous");previous.Click+=async(_,_)=>{page=Math.Max(1,page-1);await LoadStudentsAsync();};var next=MakeButton("Next");next.Click+=async(_,_)=>{page++;await LoadStudentsAsync();};top.Controls.AddRange([username,password,login,room,load,previous,next,status]);Controls.Add(grid);Controls.Add(top);grid.DataError+=(_,e)=>{e.ThrowException=false;e.Cancel=true;};}
    static Button MakeButton(string text)=>new(){Text=text,AutoSize=true,Height=36,BackColor=Color.FromArgb(2,126,126),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};
    async Task LoginAsync(){try{var response=await api.PostAsJsonAsync("/api/auth/login",new LoginRequest(username.Text,password.Text));status.Text=response.IsSuccessStatusCode?$"Signed in: {(await response.Content.ReadFromJsonAsync<LoginResponse>())?.FullName}":"Invalid login";}catch(Exception ex){status.Text=$"API unavailable: {ex.Message}";}}
    async Task LoadStudentsAsync(){if(!int.TryParse(room.Text,out var roomId)){status.Text="Enter a numeric Room ID";return;}try{var data=await api.GetFromJsonAsync<PagedResult<Student>>($"/api/rooms/{roomId}/students?page={page}&pageSize=10");if(data is null)return;page=Math.Min(page,data.TotalPages);grid.DataSource=data.Items.ToList();if(grid.Columns.Contains(nameof(Student.StudentId)))grid.Columns[nameof(Student.StudentId)].Visible=false;if(grid.Columns.Contains(nameof(Student.RoomId)))grid.Columns[nameof(Student.RoomId)].Visible=false;status.Text=$"Page {data.Page} of {data.TotalPages} • {data.TotalCount} students";}catch(Exception ex){status.Text=$"API unavailable: {ex.Message}";}}
}
