using Microsoft.Data.SqlClient;
using StudentAttendanceSystem.Models;
using StudentAttendanceSystem.Services;

namespace StudentAttendanceSystem.Forms.Shared;

public sealed class AttendanceHistoryControl:UserControl
{
    readonly AppServices s;readonly UserSession user;readonly ComboBox rooms=new(){Width=240,DropDownStyle=ComboBoxStyle.DropDownList},subjects=new(){Width=240,DropDownStyle=ComboBoxStyle.DropDownList};readonly DateTimePicker from=new(){Width=135,Value=DateTime.Today.AddMonths(-1),Format=DateTimePickerFormat.Custom,CustomFormat="dd MMM yyyy"},to=new(){Width=135,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMM yyyy"};readonly DataGridView grid=new(){Dock=DockStyle.Fill};readonly Label pageLabel=new(){AutoSize=true,Margin=new Padding(12,12,12,0),ForeColor=Ui.Muted};List<HistoryRow> rows=[];int currentPage=1;const int PageSize=10;
    public AttendanceHistoryControl(AppServices s,UserSession user){this.s=s;this.user=user;Ui.ConfigureGrid(grid);var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=76,Padding=new Padding(14,8,14,8),BackColor=Color.White,WrapContents=false};bar.Controls.AddRange([Ui.Label("Class"),rooms,Ui.Label("Course"),subjects,Ui.Label("From"),from,Ui.Label("To"),to,Ui.Button("View history",(_,_)=>Ui.Safe(SearchAsync))]);var pager=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(10,5,18,5),BackColor=Ui.Surface};pager.Controls.Add(Ui.SecondaryButton("Next",(_,_)=>{currentPage++;ShowPage();}));pager.Controls.Add(pageLabel);pager.Controls.Add(Ui.SecondaryButton("Previous",(_,_)=>{if(currentPage>1)currentPage--;ShowPage();}));var body=new Panel{Dock=DockStyle.Fill,Padding=new Padding(14),BackColor=Ui.Background};body.Controls.Add(grid);body.Controls.Add(pager);Controls.Add(body);Controls.Add(bar);Load+=(_,_)=>Ui.Safe(InitAsync);rooms.SelectedIndexChanged+=(_,_)=>Ui.Safe(SubjectsAsync);grid.DataError+=(_,e)=>{e.ThrowException=false;e.Cancel=true;};Ui.ThemeContainer(this);}
    async Task InitAsync()=>rooms.DataSource=await s.Attendance.GetAccessibleRoomsAsync(user);
    async Task SubjectsAsync(){if(rooms.SelectedItem is LookupItem r)subjects.DataSource=await s.Attendance.GetAccessibleSubjectsAsync(user,r.Id,true);}
    async Task SearchAsync(){if(rooms.SelectedItem is not LookupItem r||subjects.SelectedItem is not LookupItem sub)return;if(user.Role!=UserRole.Admin&&(user.TeacherId is null||!await s.Authorization.CanViewAttendanceAsync(user.TeacherId.Value,r.Id,sub.Id)))throw new UnauthorizedAccessException();rows=await s.Db.QueryAsync("SELECT a.AttendanceId,a.AttendanceDate,st.StudentCode,st.StudentName,a.Status,a.Remark,t.FullName RecordedBy FROM Attendance a JOIN Students st ON st.StudentId=a.StudentId JOIN Teachers t ON t.TeacherId=a.TeacherId WHERE a.RoomId=@r AND a.SubjectId=@s AND a.AttendanceDate BETWEEN @f AND @to ORDER BY a.AttendanceId",x=>new HistoryRow(x.GetInt32(0),x.GetDateTime(1).ToShortDateString(),x.GetString(2),x.GetString(3),x.GetString(4),x.IsDBNull(5)?"":x.GetString(5),x.GetString(6)),new("@r",r.Id),new("@s",sub.Id),new("@f",from.Value.Date),new("@to",to.Value.Date));currentPage=1;ShowPage();}
    void ShowPage(){var pages=Math.Max(1,(int)Math.Ceiling(rows.Count/(double)PageSize));currentPage=Math.Clamp(currentPage,1,pages);grid.DataSource=rows.Skip((currentPage-1)*PageSize).Take(PageSize).Select(x=>new{x.Date,x.Code,x.Student,x.Status,x.Remark,x.RecordedBy}).ToList();pageLabel.Text=$"Page {currentPage} of {pages}   •   {rows.Count} records";}
    sealed record HistoryRow(int Id,string Date,string Code,string Student,string Status,string Remark,string RecordedBy);
}
