using Microsoft.Data.SqlClient;
using StudentAttendanceSystem.Models;
using StudentAttendanceSystem.Services;
using StudentAttendanceSystem.Helpers;

namespace StudentAttendanceSystem.Forms.Shared;

public sealed class AttendanceHistoryControl:UserControl
{
    readonly AppServices s;readonly UserSession user;readonly ComboBox rooms=new(){Width=240,DropDownStyle=ComboBoxStyle.DropDownList},subjects=new(){Width=240,DropDownStyle=ComboBoxStyle.DropDownList};readonly DateTimePicker from=new(){Width=135,Value=new DateTime(DateTime.Today.Year,1,1),Format=DateTimePickerFormat.Custom,CustomFormat="dd MMM yyyy"},to=new(){Width=135,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMM yyyy"};readonly DataGridView grid=new(){Dock=DockStyle.Fill};readonly Label pageLabel=new(){AutoSize=true,Margin=new Padding(12,12,12,0),ForeColor=Ui.Muted};List<HistoryRow> rows=[];int currentPage=1;const int PageSize=10;
    public AttendanceHistoryControl(AppServices s,UserSession user){this.s=s;this.user=user;Ui.ConfigureGrid(grid);var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=76,Padding=new Padding(14,8,14,8),BackColor=Color.White,WrapContents=false};bar.Controls.AddRange([Ui.Label("Class"),rooms,Ui.Label("Course"),subjects,Ui.Label("From"),from,Ui.Label("To"),to,Ui.Button("View history",(_,_)=>Ui.Safe(SearchAsync)),Ui.SecondaryButton("Export all to Excel",(_,_)=>ExportExcel())]);var pager=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(10,5,18,5),BackColor=Ui.Surface};pager.Controls.Add(Ui.SecondaryButton("Next",(_,_)=>{currentPage++;ShowPage();}));pager.Controls.Add(pageLabel);pager.Controls.Add(Ui.SecondaryButton("Previous",(_,_)=>{if(currentPage>1)currentPage--;ShowPage();}));var body=new Panel{Dock=DockStyle.Fill,Padding=new Padding(14),BackColor=Ui.Background};body.Controls.Add(grid);body.Controls.Add(pager);Controls.Add(body);Controls.Add(bar);Load+=(_,_)=>Ui.Safe(InitAsync);rooms.SelectedIndexChanged+=(_,_)=>Ui.Safe(SubjectsAsync);subjects.SelectedIndexChanged+=(_,_)=>Ui.Safe(SearchAsync);from.ValueChanged+=(_,_)=>Ui.Safe(SearchAsync);to.ValueChanged+=(_,_)=>Ui.Safe(SearchAsync);grid.DataError+=(_,e)=>{e.ThrowException=false;e.Cancel=true;};Ui.ThemeContainer(this);}
    async Task InitAsync(){rooms.DataSource=await s.Attendance.GetAccessibleRoomsAsync(user);if(rooms.SelectedItem is LookupItem)await SubjectsAsync();}
    async Task SubjectsAsync(){if(rooms.SelectedItem is not LookupItem r)return;subjects.DataSource=await s.Attendance.GetAccessibleSubjectsAsync(user,r.Id,true);if(subjects.SelectedItem is LookupItem)await SearchAsync();else{rows=[];ShowPage();}}
    async Task SearchAsync(){if(rooms.SelectedItem is not LookupItem r||subjects.SelectedItem is not LookupItem sub)return;if(from.Value.Date>to.Value.Date)throw new ArgumentException("The From date must be on or before the To date.");if(user.Role!=UserRole.Admin&&(user.TeacherId is null||!await s.Authorization.CanViewAttendanceAsync(user.TeacherId.Value,r.Id,sub.Id)))throw new UnauthorizedAccessException();rows=await s.Db.QueryAsync("SELECT a.AttendanceId,a.AttendanceDate,st.StudentCode,st.StudentName,CASE WHEN a.Status='Late' THEN 'Present' WHEN a.Status='Excused' THEN 'Absent' ELSE a.Status END,a.Remark,t.FullName RecordedBy FROM Attendance a JOIN Students st ON st.StudentId=a.StudentId JOIN Teachers t ON t.TeacherId=a.TeacherId WHERE a.RoomId=@r AND a.SubjectId=@s AND a.AttendanceDate BETWEEN @f AND @to ORDER BY a.AttendanceDate DESC,st.StudentCode",x=>new HistoryRow(x.GetInt32(0),x.GetDateTime(1).ToShortDateString(),x.GetString(2),x.GetString(3),x.GetString(4),x.IsDBNull(5)?"":x.GetString(5),x.GetString(6)),new("@r",r.Id),new("@s",sub.Id),new("@f",from.Value.Date),new("@to",to.Value.Date));currentPage=1;ShowPage();}
    void ShowPage(){var pages=Math.Max(1,(int)Math.Ceiling(rows.Count/(double)PageSize));currentPage=Math.Clamp(currentPage,1,pages);grid.DataSource=rows.Skip((currentPage-1)*PageSize).Take(PageSize).Select(x=>new{x.Date,x.Code,x.Student,x.Status,x.Remark,x.RecordedBy}).ToList();pageLabel.Text=$"Page {currentPage} of {pages}   •   {rows.Count} records";}
    void ExportExcel(){if(rows.Count==0)throw new InvalidOperationException("View attendance history before exporting it.");using var dialog=new SaveFileDialog{Filter="Excel workbook (*.xlsx)|*.xlsx",DefaultExt="xlsx",AddExtension=true,FileName=$"Attendance_History_{from.Value:yyyyMMdd}_{to.Value:yyyyMMdd}.xlsx"};if(dialog.ShowDialog()!=DialogResult.OK)return;ExcelExporter.Export(dialog.FileName,"Attendance History",["Date","Registration No.","Student Name","Status","Remark","Recorded By"],rows.Select(x=>(IReadOnlyList<object?>)[x.Date,x.Code,x.Student,x.Status,x.Remark,x.RecordedBy]));MessageBox.Show("All attendance history records were exported to Excel.","Export complete",MessageBoxButtons.OK,MessageBoxIcon.Information);}
    sealed record HistoryRow(int Id,string Date,string Code,string Student,string Status,string Remark,string RecordedBy);
}
