using StudentAttendanceSystem.Models;
using StudentAttendanceSystem.Services;

namespace StudentAttendanceSystem.Forms.Shared;

public sealed class MonthlyReportControl:UserControl
{
    readonly AppServices s;readonly UserSession user;readonly bool homeRoomOnly;readonly ComboBox rooms=new(){Width=210,DropDownStyle=ComboBoxStyle.DropDownList},month=new(){Width=120,DropDownStyle=ComboBoxStyle.DropDownList},year=new(){Width=90,DropDownStyle=ComboBoxStyle.DropDownList};readonly DataGridView grid=new(){Dock=DockStyle.Fill};readonly Label pageLabel=new(){AutoSize=true,Margin=new Padding(12,12,12,0),ForeColor=Ui.Muted};List<MonthlyReportRow> rows=[];int currentPage=1;const int PageSize=10;
    public MonthlyReportControl(AppServices s,UserSession user,bool homeRoomOnly=false){this.s=s;this.user=user;this.homeRoomOnly=homeRoomOnly;Ui.ConfigureGrid(grid);month.DataSource=Enumerable.Range(1,12).Select(i=>new LookupItem(i,new DateTime(2000,i,1).ToString("MMMM"))).ToList();year.DataSource=Enumerable.Range(DateTime.Now.Year-5,7).Reverse().ToList();year.SelectedItem=DateTime.Now.Year;var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=76,Padding=new Padding(14,8,14,8),BackColor=Color.White,WrapContents=false};bar.Controls.AddRange([Ui.Label(homeRoomOnly?"My home room":"Class"),rooms,Ui.Label("Reporting month"),month,Ui.Label("Year"),year,Ui.Button("Generate report",(_,_)=>Ui.Safe(LoadReportAsync))]);var pager=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(10,5,18,5),BackColor=Ui.Surface};pager.Controls.Add(Ui.SecondaryButton("Next",(_,_)=>{currentPage++;ShowPage();}));pager.Controls.Add(pageLabel);pager.Controls.Add(Ui.SecondaryButton("Previous",(_,_)=>{if(currentPage>1)currentPage--;ShowPage();}));var body=new Panel{Dock=DockStyle.Fill,Padding=new Padding(14),BackColor=Ui.Background};body.Controls.Add(grid);body.Controls.Add(pager);Controls.Add(body);Controls.Add(bar);Load+=(_,_)=>Ui.Safe(InitAsync);grid.CellFormatting+=(_,e)=>{if(e.ColumnIndex>=0&&grid.Columns[e.ColumnIndex].DataPropertyName==nameof(MonthlyReportRow.Remark)&&e.Value?.ToString()?.Contains("below")==true){e.CellStyle!.BackColor=Color.FromArgb(255,235,235);e.CellStyle.ForeColor=Color.FromArgb(183,55,55);e.CellStyle.Font=new Font("Segoe UI Semibold",9);}};grid.DataError+=(_,e)=>{e.ThrowException=false;e.Cancel=true;};Ui.ThemeContainer(this);}
    async Task InitAsync()=>rooms.DataSource=homeRoomOnly?await s.Attendance.GetHomeRoomsAsync(user):await s.Attendance.GetAccessibleRoomsAsync(user);
    async Task LoadReportAsync(){if(rooms.SelectedItem is LookupItem r&&month.SelectedItem is LookupItem m&&year.SelectedItem is int y){rows=await s.Attendance.GetMonthlyReportAsync(user,r.Id,m.Id,y);currentPage=1;ShowPage();}}
    void ShowPage(){var pages=Math.Max(1,(int)Math.Ceiling(rows.Count/(double)PageSize));currentPage=Math.Clamp(currentPage,1,pages);grid.DataSource=rows.Skip((currentPage-1)*PageSize).Take(PageSize).ToList();pageLabel.Text=$"Page {currentPage} of {pages}   •   {rows.Count} students";}
}
