using StudentAttendanceSystem.Models;
using StudentAttendanceSystem.Services;

namespace StudentAttendanceSystem.Forms.Shared;

public sealed class StudentManagementControl:UserControl
{
    private readonly AppServices s;private readonly UserSession user;private readonly ComboBox rooms=new(){Width=220,DropDownStyle=ComboBoxStyle.DropDownList};private readonly TextBox search=new(){Width=190,PlaceholderText="Search students..."};private readonly DataGridView grid=new(){Dock=DockStyle.Fill};private readonly Label pageLabel=new(){AutoSize=true,Margin=new Padding(12,12,12,0),ForeColor=Ui.Muted};private readonly Button addButton,editButton,toggleButton;private List<StudentItem> items=[];private int currentPage=1;const int PageSize=10;
    public StudentManagementControl(AppServices s,UserSession user)
    {
        this.s=s;this.user=user;Ui.ConfigureGrid(grid);ConfigureColumns();addButton=Ui.Button("Add student",(_,_)=>Ui.Safe(AddAsync));editButton=Ui.SecondaryButton("Edit selected",(_,_)=>Ui.Safe(EditAsync));toggleButton=Ui.SecondaryButton("Activate / deactivate",(_,_)=>Ui.Safe(ToggleAsync));
        var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=68,Padding=new Padding(8)};bar.Controls.AddRange([Ui.Label("Class"),rooms,Ui.Label("Search"),search,addButton,editButton,toggleButton,Ui.SecondaryButton("Refresh",(_,_)=>Ui.Safe(LoadAsync))]);var pager=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(10,5,18,5),BackColor=Ui.Surface};pager.Controls.Add(Ui.SecondaryButton("Next",(_,_)=>{currentPage++;ApplySearch();}));pager.Controls.Add(pageLabel);pager.Controls.Add(Ui.SecondaryButton("Previous",(_,_)=>{if(currentPage>1)currentPage--;ApplySearch();}));rooms.SelectedIndexChanged+=(_,_)=>{currentPage=1;Ui.Safe(LoadAsync);};search.TextChanged+=(_,_)=>{currentPage=1;ApplySearch();};Controls.Add(grid);Controls.Add(pager);Controls.Add(bar);Load+=(_,_)=>Ui.Safe(InitAsync);grid.CellFormatting+=StatusFormatting;grid.DataBindingComplete+=(_,_)=>FillRowNumbers();grid.DataError+=(_,e)=>{e.ThrowException=false;e.Cancel=true;};
    }
    private void ConfigureColumns(){grid.AutoGenerateColumns=false;grid.Columns.Clear();grid.Columns.Add(new DataGridViewTextBoxColumn{Name="No",HeaderText="No.",ReadOnly=true,ValueType=typeof(int),FillWeight=10,MinimumWidth=55,SortMode=DataGridViewColumnSortMode.NotSortable});grid.Columns.Add(new DataGridViewTextBoxColumn{Name=nameof(StudentItem.StudentCode),HeaderText="Registration No.",DataPropertyName=nameof(StudentItem.StudentCode),ReadOnly=true,ValueType=typeof(string),FillWeight=24});grid.Columns.Add(new DataGridViewTextBoxColumn{Name=nameof(StudentItem.StudentName),HeaderText="Student Name",DataPropertyName=nameof(StudentItem.StudentName),ReadOnly=true,ValueType=typeof(string),FillWeight=34});grid.Columns.Add(new DataGridViewTextBoxColumn{Name=nameof(StudentItem.Gender),HeaderText="Gender",DataPropertyName=nameof(StudentItem.Gender),ReadOnly=true,ValueType=typeof(string),FillWeight=16});grid.Columns.Add(new DataGridViewTextBoxColumn{Name=nameof(StudentItem.RoomName),HeaderText="Class",DataPropertyName=nameof(StudentItem.RoomName),ReadOnly=true,ValueType=typeof(string),FillWeight=20});grid.Columns.Add(new DataGridViewTextBoxColumn{Name=nameof(StudentItem.IsActive),HeaderText="Status",DataPropertyName=nameof(StudentItem.IsActive),ReadOnly=true,ValueType=typeof(bool),FillWeight=16});}
    private async Task InitAsync(){rooms.DataSource=await s.Attendance.GetAccessibleRoomsAsync(user);}
    private async Task LoadAsync(){if(rooms.SelectedItem is LookupItem r){items=await s.Students.GetAsync(user,r.Id);ApplySearch();var canManage=user.Role==UserRole.Admin||(user.TeacherId is not null&&await s.Authorization.CanManageStudentsAsync(user.TeacherId.Value,r.Id));addButton.Enabled=canManage;editButton.Enabled=canManage;toggleButton.Enabled=canManage;}}
    private void ApplySearch(){var q=search.Text.Trim();var filtered=string.IsNullOrEmpty(q)?items:items.Where(x=>x.StudentCode.Contains(q,StringComparison.OrdinalIgnoreCase)||x.StudentName.Contains(q,StringComparison.OrdinalIgnoreCase)||x.Gender.Contains(q,StringComparison.OrdinalIgnoreCase)).ToList();var pages=Math.Max(1,(int)Math.Ceiling(filtered.Count/(double)PageSize));currentPage=Math.Clamp(currentPage,1,pages);grid.DataSource=filtered.Skip((currentPage-1)*PageSize).Take(PageSize).ToList();pageLabel.Text=$"Page {currentPage} of {pages}   •   {filtered.Count} students";}
    private void FillRowNumbers(){for(var i=0;i<grid.Rows.Count;i++)grid.Rows[i].Cells["No"].Value=(currentPage-1)*PageSize+i+1;}
    private async Task AddAsync(){if(rooms.SelectedItem is not LookupItem r)return;using var d=new StudentDialog();if(d.ShowDialog()!=DialogResult.OK)return;await s.Students.SaveAsync(user,null,d.Code,d.StudentName,d.Gender,r.Id,true);await LoadAsync();}
    private async Task EditAsync(){if(rooms.SelectedItem is not LookupItem r||grid.CurrentRow?.DataBoundItem is not StudentItem student)throw new InvalidOperationException("Select a student first.");using var d=new StudentDialog(student);if(d.ShowDialog()!=DialogResult.OK)return;await s.Students.SaveAsync(user,student.StudentId,d.Code,d.StudentName,d.Gender,r.Id,student.IsActive);await LoadAsync();}
    private async Task ToggleAsync(){if(rooms.SelectedItem is not LookupItem r||grid.CurrentRow?.DataBoundItem is not StudentItem student)throw new InvalidOperationException("Select a student first.");var action=student.IsActive?"mark as withdrawn / inactive":"reactivate";if(MessageBox.Show($"Do you want to {action} {student.StudentName}?","Confirm student status",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;await s.Students.SetActiveAsync(user,student.StudentId,r.Id,!student.IsActive);await LoadAsync();}
    private void StatusFormatting(object? sender,DataGridViewCellFormattingEventArgs e){if(e.RowIndex<0||grid.Columns[e.ColumnIndex].DataPropertyName!=nameof(StudentItem.IsActive)||e.Value is not bool active)return;e.Value=active?"Active":"Inactive";e.FormattingApplied=true;e.CellStyle!.BackColor=active?Color.FromArgb(229,247,240):Color.FromArgb(255,235,235);e.CellStyle.ForeColor=active?Color.FromArgb(20,110,78):Color.FromArgb(183,55,55);e.CellStyle.SelectionBackColor=e.CellStyle.BackColor;e.CellStyle.SelectionForeColor=e.CellStyle.ForeColor;}
    private sealed class StudentDialog:Form
    {
        readonly TextBox code=new(),name=new();readonly ComboBox gender=new(){DropDownStyle=ComboBoxStyle.DropDownList};public string Code=>code.Text;public string StudentName=>name.Text;public string Gender=>gender.SelectedItem?.ToString()??"Other";
        public StudentDialog(StudentItem? student=null){Ui.Configure(this,student is null?"Add Student":"Edit Student");Text=student is null?"Add Student":"Edit Student";Size=new(430,380);MinimumSize=Size;MaximizeBox=false;StartPosition=FormStartPosition.CenterParent;var p=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,Padding=new Padding(30),WrapContents=false,BackColor=Color.White};code.Width=name.Width=gender.Width=320;p.Controls.Add(Ui.Label("Student / registration number"));p.Controls.Add(code);p.Controls.Add(Ui.Label("Student name"));p.Controls.Add(name);p.Controls.Add(Ui.Label("Gender"));gender.Items.AddRange(new object[]{"Male","Female","Other"});gender.SelectedIndex=0;p.Controls.Add(gender);if(student is not null){code.Text=student.StudentCode;name.Text=student.StudentName;var existing=gender.Items.Cast<object>().Select(x=>x.ToString()).ToList().FindIndex(x=>string.Equals(x,student.Gender,StringComparison.OrdinalIgnoreCase));gender.SelectedIndex=existing>=0?existing:2;}var ok=Ui.Button("Save changes",(_,_)=>DialogResult=DialogResult.OK);ok.Width=320;p.Controls.Add(ok);Controls.Add(p);AcceptButton=ok;Ui.ThemeContainer(this);}
    }
}
