namespace StudentAttendanceSystem.Forms.Shared;

internal static class Ui
{
    public static bool IsDark{get;private set;}
    public static readonly Color Primary=Color.FromArgb(9,39,45),PrimaryLight=Color.FromArgb(13,58,64),Accent=Color.FromArgb(2,126,126),AccentLight=Color.FromArgb(222,245,243);
    public static Color Background=>IsDark?Color.FromArgb(17,24,28):Color.FromArgb(246,247,251);
    public static Color Surface=>IsDark?Color.FromArgb(27,36,41):Color.White;
    public static Color Text=>IsDark?Color.FromArgb(232,239,241):Color.FromArgb(32,37,53);
    public static Color Muted=>IsDark?Color.FromArgb(157,173,178):Color.FromArgb(119,126,145);
    public static Color Border=>IsDark?Color.FromArgb(55,69,75):Color.FromArgb(229,231,239);
    public static Button Button(string text,EventHandler click){var b=new Button{Text=text,AutoSize=true,MinimumSize=new Size(110,40),Padding=new Padding(16,7,16,7),BackColor=Accent,ForeColor=Color.White,FlatStyle=FlatStyle.Flat,Cursor=Cursors.Hand,Font=new Font("Segoe UI Semibold",9.5f),Margin=new Padding(6)};b.FlatAppearance.BorderSize=0;b.FlatAppearance.MouseOverBackColor=Color.FromArgb(1,101,101);b.FlatAppearance.MouseDownBackColor=Color.FromArgb(0,82,82);b.Click+=click;return b;}
    public static Button SecondaryButton(string text,EventHandler click){var b=Button(text,click);b.BackColor=Color.White;b.ForeColor=Text;b.FlatAppearance.BorderSize=1;b.FlatAppearance.BorderColor=Border;b.FlatAppearance.MouseOverBackColor=AccentLight;return b;}
    public static Label Label(string text)=>new(){Text=text,AutoSize=true,Margin=new Padding(8,12,6,6),ForeColor=Muted,Font=new Font("Segoe UI Semibold",9)};
    public static void Configure(Form f,string title){f.Text=title;f.BackColor=Background;f.Font=new Font("Segoe UI",10);f.ForeColor=Text;f.StartPosition=FormStartPosition.CenterScreen;f.MinimumSize=new Size(1000,650);}
    public static void ConfigureGrid(DataGridView g){g.AutoGenerateColumns=true;g.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;g.ReadOnly=true;g.AllowUserToAddRows=false;g.AllowUserToDeleteRows=false;g.AllowUserToResizeRows=false;g.SelectionMode=DataGridViewSelectionMode.FullRowSelect;g.MultiSelect=false;g.BackgroundColor=Surface;g.BorderStyle=BorderStyle.None;g.CellBorderStyle=DataGridViewCellBorderStyle.SingleHorizontal;g.GridColor=Border;g.RowHeadersVisible=false;g.RowTemplate.Height=44;g.EnableHeadersVisualStyles=false;g.ColumnHeadersHeight=46;g.ColumnHeadersBorderStyle=DataGridViewHeaderBorderStyle.None;g.ColumnHeadersDefaultCellStyle=new DataGridViewCellStyle{BackColor=IsDark?Color.FromArgb(35,46,51):Color.FromArgb(248,249,252),ForeColor=Muted,Font=new Font("Segoe UI Semibold",9.5f),SelectionBackColor=IsDark?Color.FromArgb(35,46,51):Color.FromArgb(248,249,252),SelectionForeColor=Muted,Padding=new Padding(8)};g.DefaultCellStyle=new DataGridViewCellStyle{BackColor=Surface,ForeColor=Text,SelectionBackColor=IsDark?Color.FromArgb(8,75,75):AccentLight,SelectionForeColor=Text,Padding=new Padding(8)};g.AlternatingRowsDefaultCellStyle=new DataGridViewCellStyle{BackColor=IsDark?Color.FromArgb(30,40,45):Color.FromArgb(252,252,254)};}
    public static void StyleInput(Control c){c.Font=new Font("Segoe UI",10);c.BackColor=Surface;c.ForeColor=Text;c.Margin=new Padding(6,7,12,7);if(c is TextBox t)t.BorderStyle=BorderStyle.FixedSingle;}
    public static Panel Toolbar(){return new Panel{Dock=DockStyle.Top,Height=70,Padding=new Padding(18,10,18,10),BackColor=Surface};}
    public static Panel Card(int padding=16)=>new(){BackColor=Surface,Padding=new Padding(padding),Margin=new Padding(8)};
    public static void ThemeContainer(Control root){foreach(Control c in root.Controls){if(c is TextBox or ComboBox or DateTimePicker)StyleInput(c);if(c is FlowLayoutPanel p&&p.Dock==DockStyle.Top){p.BackColor=Surface;p.Height=Math.Max(p.Height,68);p.Padding=new Padding(14,8,14,8);}ThemeContainer(c);}}
    public static void SetDarkMode(bool enabled){IsDark=enabled;}
    public static void ApplyTheme(Control root){if(root is Form or UserControl)root.BackColor=Background;foreach(Control c in root.Controls){if(c is DataGridView grid)ConfigureGrid(grid);else if(c is TextBox or ComboBox or DateTimePicker)StyleInput(c);else if(c is Button b){var isAssignmentCard=b.Width>=300&&b.Height>=70;if(b.FlatAppearance.BorderSize>0&&b.BackColor!=Accent){b.BackColor=Surface;b.ForeColor=Text;b.FlatAppearance.BorderColor=Border;b.FlatAppearance.MouseOverBackColor=IsDark?Color.FromArgb(39,52,57):AccentLight;}else if(b.BackColor!=Primary&&b.BackColor!=PrimaryLight&&!isAssignmentCard){b.BackColor=Accent;b.ForeColor=Color.White;b.FlatAppearance.MouseOverBackColor=Color.FromArgb(1,101,101);}else if(isAssignmentCard&&b.BackColor!=Accent){b.BackColor=Surface;b.ForeColor=Text;b.FlatAppearance.BorderColor=Border;}}else if(c is Panel or FlowLayoutPanel or TableLayoutPanel){var themed=c.BackColor==Color.White||c.BackColor==Color.FromArgb(246,247,251)||c.BackColor==Color.FromArgb(248,249,252)||c.BackColor==Color.FromArgb(247,249,253)||c.BackColor==Color.FromArgb(244,244,246)||c.BackColor==Color.FromArgb(27,36,41)||c.BackColor==Color.FromArgb(17,24,28)||c.BackColor==Color.FromArgb(30,40,45)||c.BackColor==Color.FromArgb(35,46,51);if(themed)c.BackColor=c.Dock==DockStyle.Fill?Background:Surface;}if(c is Label l&&l.ForeColor!=Color.White&&l.ForeColor!=Color.FromArgb(151,158,191)&&l.ForeColor!=Color.FromArgb(167,175,208))l.ForeColor=l.Font.Bold?Text:Muted;ApplyTheme(c);}}
    public static async void Safe(Func<Task> action){try{await action();}catch(Exception ex){MessageBox.Show(ex.Message,"Unable to complete action",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
}
